import localFont from "next/font/local";
// import Recoleta from '../../public/fonts/Recoleta-Black';
import Footer from "../app/components/Footer/Footer";
import Header from "../app/components/Header/Header";
import "./globals.css";
// font 2:                                                                     https://prismic.io/blog/nextjs-fonts
import { Open_Sans } from 'next/font/google';
 

// setting up the main font object:
const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/Recoleta-Black.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/Recoleta-Medium.ttf",
      weight: "300",
    },
    {
      path: "../../public/fonts/Recoleta-Light.ttf",
      weight: "200",
    },
  ],
  variable: "--font-Recoleta-Black",
  subsets: ["latin"],
});

// setting up the font 2:
const openSans = Open_Sans ( {
  subsets: ['latin'],                    
  display: 'swap'
})

export const metadata = {
  title: " NextJs | Adriano's Portfolio ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Header />
        <div className={poppins.className}>
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
